import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import { ROUTES } from "@/constants/routes";
import { isLoggedInServerSide } from "@/services/auth";

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}

export const getServerSideProps = async ({ locale, ...context }: GetServerSidePropsContext) => {
  if (!isLoggedInServerSide(context)) {
    return {
      redirect: {
        destination: ROUTES.SIGN_IN(),
        permanent: false,
      },
    };
  }

  return {
    props: {
      ...(await serverSideTranslations(locale as string, ["common"])),
    },
  };
};

export default Home;
